name: evento_ui
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  introduction_screen: ^3.0.0
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  carousel_slider: ^4.0.0
  extended_sliver: ^2.0.1
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/icon/
    - assets/images/

